### ISSUE TITLE
S3 Path Styles

### ISSUE THREAD

**Issue by GizzmoAsus** [backup-manager/backup-manager#160] opened 2020-01-29 07:19 UTC
Hi,
I'm currently leveraging your awesome library for a service that I'm building internally and have come across a slight snag.

Instead of using Amazon AWS we are using a localised version of Minio as the main S3 storage platform. In order to use your library with Minio I need to ensure the path style is directory based as opposed to DNS based.

The AWS 3 driver supports a configuration called "use_path_style_endpoint" with a boolean value, when this is set to true then it defaults to the directory path.

I've managed to get this working beautifully by adding the following to the client configuration in the `Awss3Filesystem:get()` function located at Filesystems/Awss3Filesystem.php (~line 34):

```
'use_path_style_endpoint' => isset($config['use_path_style_endpoint']) ? $config['use_path_style_endpoint'] : false
```

Is there an alternative approach with your library to achieve the same thing? If not, any objections to me creating a pull request with this change in?

**Comment by GizzmoAsus** [comment] 2020-02-10 04:41
Hi @ShawnMcCool would it be possible to get a response to this request / discussion please?

**Comment by ShawnMcCool** [comment] 2020-02-10 18:22
Hey there, sorry for the delay. I've merged it into master. If you can verify that it's working as intended in dev-master then I'll be happy to tag it.

**Comment by GizzmoAsus** [comment] 2020-02-12 10:51
Hey @ShawnMcCool, thanks for the assist, that's working beautifully in dev-master :)

**Comment by ShawnMcCool** [comment] 2020-02-12 11:20
tagged at 2.1.0

thanks for your work =)

**Closed by ShawnMcCool** 2020-02-12 11:20 UTC
